version: "3.3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/log/honeypot
  nginx: 
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - web
    links:
      - "web"
    ports: 
      - "80:80"
    volumes:
      - ./:/var/log/honeypot

